# -*- coding: utf-8 -*-
"""Data Visualization Day5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10IbKVt06N63MgPfUt7ThqV0VfcSnkqdW
"""

# What is plotly ?

"""plotly is a data visualization tool which is powerful ,easy to use and has a benefit of interactivity 
being able to export the visualizations to the plotly cloud, able to run them in the browser
interact with javascript build with dash, which is a python interface which removes the need of java script in these type of analytical web applications
you can also run these plots offline and in jupiter as well.
"""

# Where it is used ?

"""plotly is a great tool to have if working on building any type of analytical presentation or trying to interpret results
it is used for a wide range of statistical, financial, geographic, scientific, and 3-dimensional use-cases.
"""

# Make a Pie Chart of India's car company market share % values (max 6 companies market share)
import pandas as pd
import plotly
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go

labels = ['Tata','Hyundai','Maruti','renault','kia','Mahindra']
values = [7 , 17.7 , 50 , 3.3 , 5.6 , 5.8]
title= "Indias 6 heighest market share Car companies"

pie_chart = go.Figure(data=[go.Pie(labels=labels,values=values,title=title)])
pie_chart.show()

pie_chart.update_traces(
    textposition = 'inside',
    textinfo = 'percent+label'
)


plotly.offline.plot(pie_chart,filename='Piechart.html')



# Plot a Bar Chart with India's covid 19 active cases (max 10 states)

import pandas as pd
import plotly
import plotly.graph_objects as go

states = ['Maharashtra','Karnataka','Kerala','Tamil nadu','Andhra Pradesh','Uttar Pradesh','West Bengal','Delhi','Chattisghar','Rajasthan']
cases = [117575,48116,103563,35881,35871,2461,19280,1016,5330,1260]
 

bar_graph = go.Figure([go.Bar(x=states, y= cases )])
bar_graph.show()

plotly.offline.plot(bar_graph,filename='Bargraph.html')

# plot a line chart India's covid 19 case recovery (max 12 months)

import pandas as pd
import plotly
import plotly.graph_objects as go
import numpy as np

line_graph = go.Figure()


states = ['May 20','June 20','July 20','Aug 20','Sep 20','Oct 20','Nov 20','Dec 20','Jan 21','Feb 21','Mar 21','Apr 21']
cases = [57721,321781,953099,2583063,4755522,7371898,8717709,9881732,10396162,10748778,11262508,15673250]

line_graph = go.Figure(data=go.Scatter(x=states, y= cases ))
line_graph.show()

plotly.offline.plot(line_graph,filename='Linegraph.html')

